# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto

require 'google/protobuf'


descriptor_data = "\n\x0cserver.proto\"5\n\x16WorkerRequestCreateMap\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x13WorkerRequestGetMap\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x17WorkerResponseCreateMap\x12\x10\n\x08response\x18\x01 \x01(\t\"\'\n\x14WorkerResponseGetMap\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8d\x01\n\x0fMapReduceMaster\x12\x38\n\x07GetMaps\x12\x14.WorkerRequestGetMap\x1a\x15.WorkerResponseGetMap\"\x00\x12@\n\tCreateMap\x12\x17.WorkerRequestCreateMap\x1a\x18.WorkerResponseCreateMap\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

WorkerRequestCreateMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerRequestCreateMap").msgclass
WorkerRequestGetMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerRequestGetMap").msgclass
WorkerResponseCreateMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerResponseCreateMap").msgclass
WorkerResponseGetMap = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("WorkerResponseGetMap").msgclass
