# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: worker.proto for package ''

require 'grpc'
require_relative 'worker_pb'

module WorkerServer
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Worker'

    rpc :Map, ::MapInfo, ::Result
    rpc :Reduce, ::ReduceInfo, ::Result
  end

  Stub = Service.rpc_stub_class
end
