# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto

require 'google/protobuf'


descriptor_data = "\n\x0cworker.proto\"&\n\x06Result\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\"5\n\x07MapInfo\x12\x10\n\x08\x46ileName\x18\x01 \x01(\t\x12\x0c\n\x04\x46rom\x18\x02 \x01(\x03\x12\n\n\x02To\x18\x03 \x01(\x03\"*\n\nReduceInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t2B\n\x06Worker\x12\x18\n\x03Map\x12\x08.MapInfo\x1a\x07.Result\x12\x1e\n\x06Reduce\x12\x0b.ReduceInfo\x1a\x07.Resultb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

Result = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Result").msgclass
MapInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("MapInfo").msgclass
ReduceInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ReduceInfo").msgclass
